# Assignment 26 Feb "Numpy"

In [ ]:
# Consider the below code to answer further questions:

In [8]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)
array_list


array(['1', '2', '3', '4', '5'], dtype='<U1')

In [11]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [ ]:
# List is used to collect items that usually consist of elements of multiple data types.
# An array is also a vital component that collects several items of the same data type.
# List cannot manage arithmetic operations. Array can manage arithmetic operations.

In [15]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [13]:
type(array_list)

numpy.ndarray

In [14]:
type(list_)

list

In [16]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [25]:
for i in list_:
    print(i)
    

1
2
3
4
5


In [26]:
type(i)

str

In [27]:

for i in array_list:
    print(i)

1
2
3
4
5


In [28]:
type(i)

numpy.str_

In [ ]:
# Q3. Considering the following changes in the variable, array_list:

# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [29]:
array_list = np.array(object = list_, dtype = int)

In [40]:
type(array_list)

numpy.ndarray

In [33]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
list_ = [1,2,3,4,5]

In [38]:
type(list_)

list

In [35]:
array_list  = np.array(list_)

In [39]:
type(array_list)

numpy.ndarray

In [41]:
array_list = np.array(list_)

In [46]:
for i in list_:
     print(i)

1
2
3
4
5


In [47]:
type(i)

int

In [48]:
for i in array_list:
    print(i)

1
2
3
4
5


In [49]:
type(i)

numpy.int64

In [ ]:
#  Consider the below code to answer further questions:

In [43]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [50]:
num_array.shape

(2, 3)

In [51]:
num_array.size


6

In [52]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [61]:
import numpy as np
mat_zero = np.zeros((3,3))
mat_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
mat_zero.shape

(3, 3)

In [62]:
mat_zero.size

9

In [63]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [64]:
import numpy as np

In [70]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])